# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

# 3 - matris'in boyutunu öğrenin

# 4 - matris'i yeniden boyutlandırın

# 5 - matris'in boyut sayısını öğrenin
import numpy as np
matris = np.random.randint(0, 10, size=(5,))
boyut = matris.shape
yeniden_boyutlanmis_matris = matris.reshape((1, 5))
boyut_sayisi = matris.ndim

print("Matris:")
print(matris)
print("Matris Boyutu:")
print(boyut)
print("Yeniden Boyutlandırılmış Matris:")
print(yeniden_boyutlanmis_matris)
print("Matris Boyut Sayısı:")
print(boyut_sayisi)

Matris:
[6 3 2 1 3]
Matris Boyutu:
(5,)
Yeniden Boyutlandırılmış Matris:
[[6 3 2 1 3]]
Matris Boyut Sayısı:
1


# Problem 2

In [11]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

# 2 - Oluşturduğunuz matrisi parçalayın

# 3 - Parçalanmış matrisleri birleştirin
import numpy as np
matris = np.arange(1, 11, 2)
parcalar = np.array_split(matris, 2)
birlesik_matris = np.concatenate(parcalar)

print("Oluşturulan Matris:")
print(matris)
print("Parçalanan Matrisler:")
print(parcalar)
print("Birleştirilmiş Matris:")
print(birlesik_matris)

Oluşturulan Matris:
[1 3 5 7 9]
Parçalanan Matrisler:
[array([1, 3, 5]), array([7, 9])]
Birleştirilmiş Matris:
[1 3 5 7 9]


# Problem 3

In [12]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

# 2 - matris'in özelliklerini inceleyin
import numpy as np
matris = np.random.choice(np.arange(5, 101, 2), size=(10,), replace=False)
boyut = matris.shape
eleman_sayisi = matris.size
en_kucuk = np.min(matris)
en_buyuk = np.max(matris)
ortalama = np.mean(matris)

print("Matris:")
print(matris)
print("Boyut:", boyut)
print("Eleman Sayısı:", eleman_sayisi)
print("En Küçük Değer:", en_kucuk)
print("En Büyük Değer:", en_buyuk)
print("Ortalama:", ortalama)

Matris:
[97 77 23 33 85 13 63 43 31 93]
Boyut: (10,)
Eleman Sayısı: 10
En Küçük Değer: 13
En Büyük Değer: 97
Ortalama: 55.8
