# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin

# 2 - 5 elemanlı bir numpy array oluşturun

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
import numpy as np

array = np.array([4, 2, 6, 1, 3])

siralanan_array = np.sort(array)
print(siralanan_array)

[1 2 3 4 6]


# Problem 2

In [4]:

import numpy as np

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturma
dizi1 = np.array([10, 15, 30, 45, 60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturma
dizi2 = np.arange(5, 16)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturma
dizi3 = np.arange(50, 101, 5)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturma
dizi4 = np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturma
dizi5 = np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretme
dizi6 = np.linspace(0, 100, 5)

# 7- (10-30) arasında rastgele 5 tamsayı üretme
dizi7 = np.random.randint(10, 31, size=5)

# 8- [-1 ile 1] arasında 10 adet sayı üretme
dizi8 = np.random.uniform(-1, 1, size=10)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturma
matris = np.random.randint(10, 51, size=(3, 5))

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplama
satir_toplamlari = np.sum(matris, axis=1)
sutun_toplamlari = np.sum(matris, axis=0)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması
en_buyuk = np.max(matris)
en_kucuk = np.min(matris)
ortalama = np.mean(matris)

# 12- Üretilen matrisin en büyük değerinin indeksi
en_buyuk_indeks = np.argmax(matris)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçme
dizi13 = np.arange(10, 21)
ilk_uc_eleman = dizi13[:3]

# 14- Üretilen dizinin elemanlarını tersten yazdırma
tersten_yazdirma = np.flip(dizi13)

# 15- Üretilen matrisin ilk satırını seçme
ilk_satir = matris[0]

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı
eleman = matris[1, 2]

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçme
ilk_elemanlar = matris[:, 0]

# 18- Üretilen matris elemanlarının karesini alma
kareler = np.square(matris)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris = np.random.randint(-50, 51, size=(3, 5))
filtre = (matris % 2 == 0) & (matris > 0)
pozitif_cift_sayilar = matris[filtre]

print("Üretilen Matris:")
print(matris)
print("\nPozitif Çift Sayılar:")
print(pozitif_cift_sayilar)

Üretilen Matris:
[[ 29 -19  39  37  41]
 [ -3 -12   5  27 -44]
 [  3 -46 -48  -8  30]]

Pozitif Çift Sayılar:
[30]
